// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type cb_read func(c.Int, c.Long, *const_cb_buf)

type cb_poll func(*const_cb_stat, *const_cb_value)

type cb_recv func(*const_cb_buf, c.Int)

type cb_log func(*c.ConstChar, *cb_buf)

type cb_write func(*const_cb_buf, c.UInt)

//so:extern cb_buf
type cb_buf struct {
	base *c.Char
	len c.ULong
}

//so:extern cb_stat
type cb_stat struct {
	size c.Long
}

//so:extern union cb_value
type cb_value struct {
	i c.Long
	d float64
}

//so:extern const cb_buf
type const_cb_buf struct {
	base *c.Char
	len c.ULong
}

//so:extern const cb_stat
type const_cb_stat struct {
	size c.Long
}

//so:extern const union cb_value
type const_cb_value struct {
	i c.Long
	d float64
}

//so:extern struct cb_ops
type cb_ops struct {
	on_read func(*const_cb_buf)
	version c.Int
}

//so:extern cb_send
func cb_send(buf *cb_buf, flags c.Int)

//so:extern cb_start
func cb_start(fd c.Int, read_cb func(c.Int, c.Long, *const_cb_buf))

//so:extern cb_each
func cb_each(fn func(*const_cb_stat))
