// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern AUDIO_CHANNELS
const AUDIO_CHANNELS = 2

//so:extern audio_open
func audio_open(channels c.Int)
