// Code generated by "so bind"; DO NOT EDIT.
// sobind: 5 opaque

package main

import "solod.dev/so/c"
var _ c.Char

type on_data func(*const_buf_t, *const_word)

//so:extern struct client
type client struct {
	in *stream
	chunk *buf_t
}

// sobind: opaque struct stream, declared outside the binding
//so:extern struct stream
type stream struct {}

// sobind: opaque buf_t, declared outside the binding
//so:extern buf_t
type buf_t struct {}

// sobind: opaque union word, declared outside the binding
//so:extern union word
type word struct {}

// sobind: opaque const buf_t, declared outside the binding
//so:extern const buf_t
type const_buf_t struct {}

// sobind: opaque const union word, declared outside the binding
//so:extern const union word
type const_word struct {}

//so:extern dump
func dump(s *stream)

//so:extern fill
func fill(b *buf_t, w *word) c.Int
