// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type on_data func(*const_buf_t, *const_word)

//so:extern struct client
type client struct {
	in *stream
	chunk *buf_t
}

//so:extern struct stream
type stream struct {}

//so:extern buf_t
type buf_t struct {}

//so:extern union word
type word struct {}

//so:extern const buf_t
type const_buf_t struct {}

//so:extern const union word
type const_word struct {}

//so:extern dump
func dump(s *stream)

//so:extern fill
func fill(b *buf_t, w *word) c.Int
