// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type on_error func(c.Int, *c.ConstChar)

type compare func(*c.ConstVoid, *c.ConstVoid) c.Int

//so:extern reset
func reset() {
}

//so:extern set_error_handler
func set_error_handler(handler func(c.Int, *c.ConstChar)) {
	_ = handler
}

//so:extern version
func version() c.Int {
	return 0
}

//so:extern set_level
func set_level(level c.Int) {
	_ = level
}

//so:extern checksum
func checksum(data string, size c.ULong) c.LongLong {
	_, _ = data, size
	return 0
}

//so:extern find
func find(name string, weight float64) *c.Char {
	_, _ = name, weight
	return nil
}

//so:extern log_printf
func log_printf(fmt string, args ...any) c.Int {
	_, _ = fmt, args
	return 0
}
