// Code generated by "so bind"; DO NOT EDIT.
// sobind: 1 inlined

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern decl_only
func decl_only(x c.Int) c.Int

// sobind: inlined plain_inline, the symbol has to come from the linked library
//so:extern plain_inline
func plain_inline(x c.Int) c.Int

//so:extern extern_inline
func extern_inline(x c.Int) c.Int

//so:extern static_inline
func static_inline(x c.Int) c.Int

//so:extern static_only
func static_only(x c.Int) c.Int
