// Code generated by "so bind"; DO NOT EDIT.
// sobind: 5 skipped

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern METER
const METER = 1

//so:extern SECOND
const SECOND = 2

// sobind: skipped AREA, the value is a float expression

//so:extern BOUND
const BOUND = 4095

//so:extern BYTE_MAX
const BYTE_MAX = 0x1p8

//so:extern CAPACITY
const CAPACITY = 4096

// sobind: skipped DOUBLED, the value is a float expression

//so:extern ENABLED
const ENABLED = 1

//so:extern EPSILON
const EPSILON = 1e-9

//so:extern FACTOR
const FACTOR = 0.5

//so:extern HALF
const HALF = .5

//so:extern LIMIT
const LIMIT = 4095

//so:extern MARGIN
const MARGIN = 0.25

//so:extern MAX_SIZE
const MAX_SIZE = 4096

//so:extern OFFSET
const OFFSET = -1.5

//so:extern PRECISE
const PRECISE = 1.0

//so:extern RATIO
const RATIO = 0.5

//so:extern SCALE
const SCALE = 0.5

// sobind: skipped TAIL, the value is a string expression

// sobind: skipped THIRD, the value is a float expression

//so:extern WHOLE
const WHOLE = 5.

// sobind: skipped WIDE, the value is a wide string

//so:extern GREETING
var GREETING *c.ConstChar // "hello" " world"

//so:extern QUOTED
var QUOTED *c.ConstChar // "say \"hi\""

//so:extern TITLE
var TITLE *c.ConstChar // "1.2.3"

//so:extern VERSION
var VERSION *c.ConstChar // "1.2.3"
