// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern ENABLED
const ENABLED = 1

//so:extern LIMIT
const LIMIT = 4095

//so:extern MAX_SIZE
const MAX_SIZE = 4096

//so:extern VERSION
const VERSION = "1.2.3"
