// Code generated by "so bind"; DO NOT EDIT.
// sobind: 5 opaque, 2 skipped, 1 guessed

package main

import "solod.dev/so/c"
var _ c.Char

// sobind: skipped transform, param z has an unmappable type

// sobind: opaque struct flags, field visible is a bitfield
//so:extern struct flags
type flags struct {}

// sobind: opaque struct packet, has an unnamed field
//so:extern struct packet
type packet struct {}

// sobind: opaque struct sample, field point has an anonymous struct type
//so:extern struct sample
type sample struct {}

// sobind: opaque struct wave, field amp has an unmappable type
//so:extern struct wave
type wave struct {}

// sobind: opaque struct blob, has a flexible array member
//so:extern struct blob
type blob struct {}

// sobind: skipped build_id, the type is unmappable

// sobind: guessed scale, param z has an unmappable type, mapped to any; the result type is unmappable, so the function returns nothing
//so:extern scale
func scale(z any, n c.Int)
