// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type sqlite3_callback func(any, c.Int, **c.Char, **c.Char) c.Int

//so:extern sqlite3
type sqlite3 struct {}

//so:extern sqlite3_file
type sqlite3_file struct {
	pMethods *sqlite3_io_methods
}

//so:extern struct sqlite3_io_methods
type sqlite3_io_methods struct {
	iVersion c.Int
	xClose func(*sqlite3_file) c.Int
	xRead func(*sqlite3_file, any, c.Int, c.LongLong) c.Int
	xWrite func(*sqlite3_file, any, c.Int, c.LongLong) c.Int
	xTruncate func(*sqlite3_file, c.LongLong) c.Int
	xSync func(*sqlite3_file, c.Int) c.Int
	xFileSize func(*sqlite3_file, *c.LongLong) c.Int
	xLock func(*sqlite3_file, c.Int) c.Int
	xUnlock func(*sqlite3_file, c.Int) c.Int
	xCheckReservedLock func(*sqlite3_file, *c.Int) c.Int
	xFileControl func(*sqlite3_file, c.Int, any) c.Int
	xSectorSize func(*sqlite3_file) c.Int
	xDeviceCharacteristics func(*sqlite3_file) c.Int
	xShmMap func(*sqlite3_file, c.Int, c.Int, c.Int, *any) c.Int
	xShmLock func(*sqlite3_file, c.Int, c.Int, c.Int) c.Int
	xShmBarrier func(*sqlite3_file)
	xShmUnmap func(*sqlite3_file, c.Int) c.Int
	xFetch func(*sqlite3_file, c.LongLong, c.Int, *any) c.Int
	xUnfetch func(*sqlite3_file, c.LongLong, any) c.Int
}

//so:extern sqlite3_value
type sqlite3_value struct {}

//so:extern sqlite3_context
type sqlite3_context struct {}

//so:extern SQLITE_VERSION
const SQLITE_VERSION = "3.45.0"

//so:extern SQLITE_VERSION_NUMBER
const SQLITE_VERSION_NUMBER = 3045000

//so:extern sqlite3_libversion
func sqlite3_libversion() *c.ConstChar

//so:extern sqlite3_sourceid
func sqlite3_sourceid() *c.ConstChar

//so:extern sqlite3_libversion_number
func sqlite3_libversion_number() c.Int

//so:extern sqlite3_compileoption_used
func sqlite3_compileoption_used(zOptName string) c.Int

//so:extern sqlite3_compileoption_get
func sqlite3_compileoption_get(N c.Int) *c.ConstChar

//so:extern sqlite3_threadsafe
func sqlite3_threadsafe() c.Int

//so:extern sqlite3_close
func sqlite3_close(arg0 *sqlite3) c.Int

//so:extern sqlite3_close_v2
func sqlite3_close_v2(arg0 *sqlite3) c.Int

//so:extern sqlite3_exec
func sqlite3_exec(arg0 *sqlite3, sql string, callback func(any, c.Int, **c.Char, **c.Char) c.Int, arg3 any, errmsg **c.Char) c.Int

//so:extern sqlite3_create_function
func sqlite3_create_function(db *sqlite3, zFunctionName string, nArg c.Int, eTextRep c.Int, pApp any, xFunc func(*sqlite3_context, c.Int, **sqlite3_value), xStep func(*sqlite3_context, c.Int, **sqlite3_value), xFinal func(*sqlite3_context)) c.Int

//so:extern sqlite3_create_filename
func sqlite3_create_filename(zDatabase string, zJournal string, zWal string, nParam c.Int, azParam **c.ConstChar) *c.ConstChar

//so:extern sqlite3_free_filename
func sqlite3_free_filename(arg0 string)

//so:extern sqlite3_win32_set_directory
func sqlite3_win32_set_directory(type_ c.ULong, zValue any) c.Int
