// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type sqlite3_callback = func(any, int32, **c.Char, **c.Char) int32

//so:extern sqlite3
type sqlite3 struct {}

//so:extern sqlite3_file
type sqlite3_file struct {
	pMethods *sqlite3_io_methods
}

//so:extern sqlite3_io_methods
type sqlite3_io_methods struct {
	iVersion int32
	xClose func(*sqlite3_file) int32
	xRead func(*sqlite3_file, any, int32, int64) int32
	xWrite func(*sqlite3_file, any, int32, int64) int32
	xTruncate func(*sqlite3_file, int64) int32
	xSync func(*sqlite3_file, int32) int32
	xFileSize func(*sqlite3_file, *int64) int32
	xLock func(*sqlite3_file, int32) int32
	xUnlock func(*sqlite3_file, int32) int32
	xCheckReservedLock func(*sqlite3_file, *int32) int32
	xFileControl func(*sqlite3_file, int32, any) int32
	xSectorSize func(*sqlite3_file) int32
	xDeviceCharacteristics func(*sqlite3_file) int32
	xShmMap func(*sqlite3_file, int32, int32, int32, *any) int32
	xShmLock func(*sqlite3_file, int32, int32, int32) int32
	xShmBarrier func(*sqlite3_file)
	xShmUnmap func(*sqlite3_file, int32) int32
	xFetch func(*sqlite3_file, int64, int32, *any) int32
	xUnfetch func(*sqlite3_file, int64, any) int32
}

//so:extern sqlite3_value
type sqlite3_value struct {}

//so:extern sqlite3_context
type sqlite3_context struct {}

//so:extern SQLITE_VERSION
const SQLITE_VERSION = "3.45.0"

//so:extern SQLITE_VERSION_NUMBER
const SQLITE_VERSION_NUMBER = 3045000

//so:extern sqlite3_libversion
func sqlite3_libversion() *c.CChar {
	return nil
}

//so:extern sqlite3_sourceid
func sqlite3_sourceid() *c.CChar {
	return nil
}

//so:extern sqlite3_libversion_number
func sqlite3_libversion_number() int32 {
	return 0
}

//so:extern sqlite3_compileoption_used
func sqlite3_compileoption_used(zOptName string) int32 {
	_ = zOptName
	return 0
}

//so:extern sqlite3_compileoption_get
func sqlite3_compileoption_get(N int32) *c.CChar {
	_ = N
	return nil
}

//so:extern sqlite3_threadsafe
func sqlite3_threadsafe() int32 {
	return 0
}

//so:extern sqlite3_close
func sqlite3_close(arg0 *sqlite3) int32 {
	_ = arg0
	return 0
}

//so:extern sqlite3_close_v2
func sqlite3_close_v2(arg0 *sqlite3) int32 {
	_ = arg0
	return 0
}

//so:extern sqlite3_exec
func sqlite3_exec(arg0 *sqlite3, sql string, callback func(any, int32, **c.Char, **c.Char) int32, arg3 any, errmsg **c.Char) int32 {
	_, _, _, _, _ = arg0, sql, callback, arg3, errmsg
	return 0
}

//so:extern sqlite3_create_function
func sqlite3_create_function(db *sqlite3, zFunctionName string, nArg int32, eTextRep int32, pApp any, xFunc func(*sqlite3_context, int32, **sqlite3_value), xStep func(*sqlite3_context, int32, **sqlite3_value), xFinal func(*sqlite3_context)) int32 {
	_, _, _, _, _, _, _, _ = db, zFunctionName, nArg, eTextRep, pApp, xFunc, xStep, xFinal
	return 0
}

//so:extern sqlite3_create_filename
func sqlite3_create_filename(zDatabase string, zJournal string, zWal string, nParam int32, azParam **c.CChar) *c.CChar {
	_, _, _, _, _ = zDatabase, zJournal, zWal, nParam, azParam
	return nil
}

//so:extern sqlite3_free_filename
func sqlite3_free_filename(arg0 string) {
	_ = arg0
}

//so:extern sqlite3_win32_set_directory
func sqlite3_win32_set_directory(type_ uint64, zValue any) int32 {
	_, _ = type_, zValue
	return 0
}
