// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type uv_close_cb func(*uv_loop_t)

//so:extern uv_loop_t
type uv_loop_t struct {
	active_handles c.Int
	iVersion c.Int
	type_ c.Int `c:"type"`
}

//so:extern uv_buf_t
type uv_buf_t struct {
	base *c.Char
	len c.ULong
}

//so:extern UV_RUN_DEFAULT
const UV_RUN_DEFAULT = 0

//so:extern UV_RUN_ONCE
const UV_RUN_ONCE = 1

//so:extern UV_RUN_NOWAIT
const UV_RUN_NOWAIT = 2

//so:extern UV_3DNOW
const UV_3DNOW = 1

//so:extern UV_VERSION_MAJOR
const UV_VERSION_MAJOR = 1

//so:extern uv_loop_size
var uv_loop_size c.Int

//so:extern uv_run
func uv_run(loop *uv_loop_t, mode c.Int) c.Int

//so:extern uv_loop_close
func uv_loop_close(loop *uv_loop_t) c.Int

//so:extern uv_open_v2
func uv_open_v2(path string, flags c.Int) c.Int

//so:extern uv_err_name
func uv_err_name(err c.Int) *c.ConstChar
