// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type Close_cb func(*Loop_t)

//so:extern uv_loop_t
type Loop_t struct {
	Active_handles c.Int `c:"active_handles"`
	IVersion c.Int `c:"iVersion"`
	Type c.Int `c:"type"`
}

//so:extern uv_buf_t
type Buf_t struct {
	Base *c.Char `c:"base"`
	Len c.ULong `c:"len"`
}

//so:extern UV_RUN_DEFAULT
const RUN_DEFAULT = 0

//so:extern UV_RUN_ONCE
const RUN_ONCE = 1

//so:extern UV_RUN_NOWAIT
const RUN_NOWAIT = 2

//so:extern UV_3DNOW
const UV_3DNOW = 1

//so:extern UV_VERSION_MAJOR
const VERSION_MAJOR = 1

//so:extern uv_loop_size
var Loop_size c.Int

//so:extern uv_run
func Run(loop *Loop_t, mode c.Int) c.Int

//so:extern uv_loop_close
func Loop_close(loop *Loop_t) c.Int

//so:extern uv_open_v2
func Open_v2(path string, flags c.Int) c.Int

//so:extern uv_err_name
func Err_name(err c.Int) *c.ConstChar
