// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

type CloseCb func(*Loop)

//so:extern uv_loop_t
type Loop struct {
	ActiveHandles c.Int `c:"active_handles"`
	IVersion c.Int `c:"iVersion"`
	Type c.Int `c:"type"`
}

//so:extern uv_buf_t
type Buf struct {
	Base *c.Char `c:"base"`
	Len c.ULong `c:"len"`
}

//so:extern UV_RUN_DEFAULT
const RunDefault = 0

//so:extern UV_RUN_ONCE
const RunOnce = 1

//so:extern UV_RUN_NOWAIT
const RunNowait = 2

//so:extern UV_3DNOW
const Uv3dnow = 1

//so:extern UV_VERSION_MAJOR
const VersionMajor = 1

//so:extern uv_loop_size
var LoopSize c.Int

//so:extern uv_run
func Run(loop *Loop, mode c.Int) c.Int

//so:extern uv_loop_close
func LoopClose(loop *Loop) c.Int

//so:extern uv_open_v2
func OpenV2(path string, flags c.Int) c.Int

//so:extern uv_err_name
func ErrName(err c.Int) *c.ConstChar
