// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern struct Scalars
type Scalars struct {
	flag bool
	ch c.Char
	sch c.SChar
	uch c.UChar
	sh c.Short
	ush c.UShort
	i c.Int
	ui c.UInt
	l c.Long
	ul c.ULong
	ll c.LongLong
	ull c.ULongLong
	f float32
	d float64
}

//so:extern struct Sized
type Sized struct {
	i8 int8
	i16 int16
	i32 int32
	i64 int64
	u8 uint8
	u16 uint16
	u32 uint32
	u64 uint64
	addr uintptr
}

//so:extern struct Target
type Target struct {
	size c.Size
	nread c.SSize
	delta c.Ptrdiff
	addr c.Intptr
	ld c.LongDouble
}

//so:extern struct Buf
type Buf struct {
	data *uint8
	size uint64
	name *c.Char
	label *c.Char
	user any
	nums [4]int32
}

//so:extern MODE_OFF
const MODE_OFF = 0

//so:extern MODE_ON
const MODE_ON = 1

//so:extern process
func process(buf *Buf, mode c.Int, n c.Size, msg string) c.Int

//so:extern read_buf
func read_buf(buf *Buf, dst any, n c.Size) c.SSize

//so:extern generichash
func generichash(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong, key *c.UChar, keylen c.Size) c.Int
