// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern struct point
type point struct {
	x c.Int
	y c.Int
}

//so:extern add
func add(a c.Int, b c.Int) c.Int
