// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern CommonEvent
type CommonEvent struct {
	type_ uint32 `c:"type"`
	timestamp uint64
}

//so:extern DisplayEvent
type DisplayEvent struct {
	type_ uint32 `c:"type"`
	timestamp uint64
	data1 int32
	data2 int32
}

//so:extern Event
type Event struct {
	type_ uint32 `c:"type"`
	common CommonEvent
	display DisplayEvent
}

//so:extern Value
type Value struct {
	num int64
	real float64
	str *c.Char
}

//so:extern Slot
type Slot struct {
	index int32
	value Value
}

//so:extern Item
type Item struct {
	range_ int32 `c:"range"`
	value Value
}

//so:extern poll_event
func poll_event(event *Event) int32 {
	_ = event
	return 0
}

//so:extern value_real
func value_real(val *Value) float64 {
	_ = val
	return 0
}
