// Code generated by "so bind"; DO NOT EDIT.

package main

import "solod.dev/so/c"
var _ c.Char

//so:extern CommonEvent
type CommonEvent struct {
	type_ c.UInt `c:"type"`
	timestamp c.ULongLong
}

//so:extern DisplayEvent
type DisplayEvent struct {
	type_ c.UInt `c:"type"`
	timestamp c.ULongLong
	data1 c.Int
	data2 c.Int
}

//so:extern Event
type Event struct {
	type_ c.UInt `c:"type"`
	common CommonEvent
	display DisplayEvent
}

//so:extern Value
type Value struct {
	num c.LongLong
	real float64
	str *c.Char
}

//so:extern union Slot
type Slot struct {
	index c.Int
	value Value
}

//so:extern struct Item
type Item struct {
	range_ c.Int `c:"range"`
	value Value
}

//so:extern poll_event
func poll_event(event *Event) c.Int {
	_ = event
	return 0
}

//so:extern value_real
func value_real(val *Value) float64 {
	_ = val
	return 0
}
